### ISSUE TITLE
Performing multiple requests with axios-observable

### ISSUE THREAD

**Issue by adripanico** [zhaosiyang/axios-observable#13]
Hello,

This is not actually an issue but a question on how to properly manage multiple requests that should be resolved at once (like with promise.all()).

I've something like this:

```
import Axios from 'axios-observable';
import { AxiosObservable } from 'axios-observable/dist/axios-observable.interface';
import {forkJoin, from, Observable} from 'rxjs';
import { AxiosResponse } from 'axios';

export interface IRequestOptions {
  skipAuthHeader?: boolean;
}

const get = <T>(url: string, opts?: IRequestOptions): AxiosObservable<T> => {
  return Axios.get<T>(url, getRequestConfig(opts));
};

const getAll = <T>(urls: string[], opts?: IRequestOptions): Observable<AxiosResponse[]> => {
  return forkJoin(
    urls.map(url => from(Axios.get<T>(url, getRequestConfig(opts))))
  );
}
```

While this is working fine, I don't like to have different returned types. I actually want to wrap `get` and `getAll` methods together, although maybe I've not think on this properly.

On the other hand, I'm not sure if with this approach I'm losing the advantages of AxiosObservable like cancel the pending requests when all subscriptions have been cancelled.

So, the questions here is, do you have some advice or workaround on how to manage this situations? 

Thanks!

**Comment by zhaosiyang** [comment]
My apology for the late reply. Somehow I didn't get an email about this issue.
- To avoid introducing a new type, you can try `combineLatest` instead of `forkJoin`.
- Theoretically, this approach should not affect the request cancelling. You can try running this in Chrome. Open dev tool and go to Network tab. If the request is cancelled successfully, it will show "Cancelled".
