### ISSUE TITLE
README example mistake

### ISSUE THREAD

**Issue by DJDaveMark** [zhaosiyang/axios-observable#36]
In the [example](https://github.com/zhaosiyang/axios-observable#example), isn't the following:

```// Optionally the request above could also be done as
Axios.get('/user?ID=12345'), {
    params: {
      ID: 12345
    }
  })
  [...]
  ```

supposed to be:

```// Optionally the request above could also be done as
Axios.get('/user'), {
    params: {
      ID: 12345
    }
  })
  [...]
  ```

**Comment by rchl-pttrsn** [comment]
Other examples, I imported the latest version, `2.0.0` yesterday:

**imports**
```
import Axios from  'axios-observable';
// or const Axios = require('axios-observable').Axios;
```
This is what I had to use:

```
import { Axios } from  'axios-observable';
```

**Cancel via unsubscribe**
The unsubscribe example is misleading since this is a stand alone example. With the nature of Observables, calling `subscription.unsubscribe();` will occur before the subscription gets data. To prevent confusion, please see request below.

```
const subscription = Axios.get('/user/12345').subscribe(response => console.log(response));

subscription.unsubscribe();
```

**Cancellation question**: Would `take(1)` or functions like that be effective for cancellation or will that override re-try?

**Request:**
Have a sample app to demonstrate how this works holistically. Great for those who don't have experience using `Axios` or who wants to tests this as a standalone module with only your repo as a dependency. 

**I am happy to make these updates and will need confirmation on the following:**
-  Is `import Axios from  'axios-observable';` still valid or was the issue my setup? (npm, node v18.19.1, using javascript)
- What directory should a sample exist? I see playground.

**Comment by zhaosiyang** [comment]
Hi @rchl-pttrsn 
Thanks for your feedback.
1. Both `import Axios from  'axios-observable';` and `import { Axios } from  'axios-observable';` are valid and should be working
2. I don't see any confusion with respect to the example of the "cancel via unsubscribe". If there are any confusions, it should be coming from the example, but from the misunderstanding of the "cancellation" itself, which we can not avoid. This doc is just providing a simple example letting people know how to cancel, instead of "what is cancellation".
